// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {});

  document.onkeypress = function(event) {
    var char, query;
    query = document.querySelector('#query');
    char = String.fromCharCode(event.charCode);
    if (char === "/") {
      query.focus();
      query.value = "";
      return event.preventDefault();
    }
  };

  document.onfocus = function() {
    var query;
    alert("xx");
    query = document.querySelector('#query');
    query.value = "";
    return query.focus();
  };

  document.onkeydown = function(event) {
    var elem;
    switch (false) {
      case event.keyCode !== 13:
        elem = document.querySelector('.item.show a');
        if (elem != null) {
          return window.open(elem.href, "_blank");
        }
        break;
      case event.keyCode !== 27:
        return document.querySelector('#query').blur();
    }
  };

}).call(this);

/*
//@ sourceMappingURL=focus.map
*/
