// Generated by CoffeeScript 1.6.3
(function() {
  var list;

  define(function(require, exports) {
    return exports.list = list;
  });

  list = {
    express: {
      name: "Expressjs.org",
      link: "http://expressjs.com/"
    },
    coffeescript: {
      name: "CoffeeScript.org",
      link: "http://coffeescript.org"
    },
    coffeescriptdn: {
      name: "CoffeeScript Chinese",
      link: "http://coffee-script.org"
    },
    ractive: {
      name: "Ractive.org",
      link: "http://ractivejs.org"
    },
    ractiveWiki: {
      name: "Ractive Wiki",
      link: "https://github.com/RactiveJS/Ractive/wiki/_pages"
    },
    requirejs: {
      name: "RequireJS",
      link: "http://requirejs.org"
    },
    golangDoc: {
      name: "Go Language doc",
      link: "http://golang.org/doc/"
    },
    webGo: {
      name: "Web.go",
      link: "http://webgo.io/"
    },
    overAPI: {
      name: "OverAPI",
      link: "http://overapi.com/"
    },
    chromeExtension: {
      name: "Chrome Extension",
      link: "http://developer.chrome.com/extensions/index.html"
    },
    learnXY: {
      name: "Learn X in Y minutes",
      link: "http://learnxinyminutes.com/"
    },
    chromeConsole: {
      name: "Using the Console",
      link: "https://developers.google.com/chrome-developer-tools/docs/console"
    },
    jadeRefernce: {
      name: "Jade Reference",
      link: "http://jade-lang.com/reference/"
    },
    seajsIssues: {
      name: "SeaJS Issues",
      link: "http://jiyinyiyong.github.io/seajs-issues/"
    },
    seajsOrg: {
      name: "SeaJS Docs",
      link: "http://seajs.org/docs/#docs"
    },
    semanticUI: {
      name: "Semantic UI",
      link: "http://semantic-ui.com/"
    },
    nodejsAPI: {
      name: "Node.js Manual & Documentation",
      link: "http://nodejs.org/docs/latest/api/"
    }
  };

}).call(this);

/*
//@ sourceMappingURL=sites.map
*/
